---
title: "PCA code"
output: html_document
date: '2022-05-02'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PCA code


```{r}
pca1$x[1,]

(x[1,1]-pca1$center[1])/pca1$scale[1] * pca1$rotation[1,1] + (x[1,2]-pca1$center[2])/pca1$scale[2] * pca1$rotation[2,1] + (x[1,3]-pca1$center[3])/pca1$scale[3] * pca1$rotation[3,1] + (x[1,4]-pca1$center[4])/pca1$scale[4] * pca1$rotation[4,1] + 
  (x[1,5]-pca1$center[5])/pca1$scale[5] * pca1$rotation[5,1] + (x[1,6]-pca1$center[6])/pca1$scale[6] * pca1$rotation[6,1] + 
  (x[1,7]-pca1$center[7])/pca1$scale[7] * pca1$rotation[7,1] + (x[1,8]-pca1$center[8])/pca1$scale[8] * pca1$rotation[8,1] +
  (x[1,9]-pca1$center[9])/pca1$scale[9] * pca1$rotation[9,1] + (x[1,10]-pca1$center[10])/pca1$scale[10] * pca1$rotation[10,1]


ggplot(pca.scores, aes(PC1, PC2, color = Class, shape = Class)) +
 geom_point() + theme_bw() +
 labs(title = "Cancer gene PCA scores, PC1 and PC2", x = "PC1 score", y = "PC2 sco
re") + geom_hline(yintercept =  0, linetype = "dotted") + geom_vline(xintercept = 0, linetype = "dotted") +
geom_segment(aes(x=0,y=0,xend=10*pca1$rotation[1,1],yend=10*pca1$rotation[1,2],color="BRCA"),size=2,arrow = arrow())+
geom_segment(aes(x=0,y=0,xend=10*pca1$rotation[2,1],yend=10*pca1$rotation[2,2],color="COAD"),size=2,arrow = arrow())+
geom_segment(aes(x=0,y=0,xend=10*pca1$rotation[3,1],yend=10*pca1$rotation[3,2],color="KIRC"),size=2,arrow = arrow()) +
geom_segment(aes(x=0,y=0,xend=10*pca1$rotation[9,1],yend=10*pca1$rotation[9,2],color="LUAD"),size=2,arrow = arrow()) +
geom_segment(aes(x=0,y=0,xend=10*pca1$rotation[10,1],yend=10*pca1$rotation[10,2],color="PRAD"),size=2,arrow = arrow()) 
```

